apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
  namespace: karpenter
spec:
  ttlSecondsAfterEmpty: 60
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values: [t3.medium]
  labels:
    managed-by: karpenter
  providerRef:
    name: default