apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
  namespace: karpenter
spec:
  subnetSelector:
    Name: "linus-sandbox-eks-private-sg"
  securityGroupSelector:
    Name: "eks-cluster-sg-linus-sandbox-eks-cluster*"