apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
  namespace: karpenter
spec:
  ttlSecondsAfterEmpty: 60
  requirements:
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values: ["t", "m"]
    - key: karpenter.k8s.aws/instance-cpu
      operator: In
      values: ["4", "8", "16", "32"]
    - key: kubernetes.io/os
      operator: In
      values: ["linux"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
    - key: karpenter.sh/capacity-type
      operator: In		
      values: ["spot"]
  labels:
    managed-by: karpenter
  providerRef:
    name: default