apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
  namespace: karpenter
spec:
  ttlSecondsAfterEmpty: 60
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - t3.medium
    - key: kubernetes.io/os
	    operator: In
      values:
        - linux
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
    - key: karpenter.sh/capacity-type
      operator: In		
      values:
        - spot
  labels:
    managed-by: karpenter
  providerRef:
    name: default